# Generated by Django 4.2 on 2024-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('city', models.CharField(choices=[('Almaty', 'Алматы'), ('Astana', 'Астана'), ('Karaganda', 'КАраганда'), ('Shymkent', 'Шымкент')], verbose_name='Город')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'db_table': 'areas',
            },
        ),
    ]
