# Generated by Django 4.2 on 2024-08-26 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_at', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('age_limit', models.CharField(choices=[('0_', 'Без ограничений'), ('6_', 'от 6 лет'), ('12_', 'от 12 лет'), ('16_', 'от 16 лет'), ('18_', 'от 18 лет'), ('21_', 'от 21 года')], verbose_name='Возрастное огранчиение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('schema', models.ImageField(upload_to='schemas', verbose_name='Схема площадки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество доступных мест')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('slug', models.SlugField(blank=True, max_length=200, unique_for_date='start_at', verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.area', verbose_name='Площадка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=64, null=True, verbose_name='Секция')),
                ('row', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ряд')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена за место')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Посадка',
                'verbose_name_plural': 'Посадки',
                'db_table': 'landings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('seat', models.CharField(max_length=32, verbose_name='Место')),
                ('status', models.CharField(choices=[('Active', 'Активный'), ('Used', 'Использованный'), ('Expired', 'Просроченный')], default=('Active', 'Активный'), verbose_name='Статус использования')),
                ('bought_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время покупки')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.landing', verbose_name='Посадка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'db_table': 'tickets',
            },
        ),
    ]
