# Generated by Django 4.2 on 2024-08-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='seat_type',
            field=models.CharField(choices=[('Ordinary', 'Обычное'), ('VIP', 'ВИП'), ('Discounted', 'Уцененное')], default=('Ordinary', 'Обычное'), verbose_name='Тип места'),
        ),
        migrations.AddField(
            model_name='landing',
            name='seats',
            field=models.JSONField(default=list, verbose_name='Список мест'),
        ),
    ]
