# Generated by Django 4.2 on 2024-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_event_landing_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='event',
            name='schema',
            field=models.ImageField(blank=True, null=True, upload_to='schemas', verbose_name='Схема площадки'),
        ),
    ]
