# Generated by Django 4.2 on 2024-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_landing_seat_type_landing_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='seats',
            field=models.JSONField(blank=True, default=list, verbose_name='Список мест'),
        ),
    ]
