# Generated by Django 4.2 on 2024-08-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_landing_seats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landing',
            unique_together={('event', 'section', 'row', 'seat_type')},
        ),
    ]
