# Generated by Django 4.2 on 2024-08-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_landing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landing',
            unique_together={('event', 'section', 'row')},
        ),
        migrations.RemoveField(
            model_name='landing',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='landing',
            name='seats',
        ),
        migrations.CreateModel(
            name='SpecialSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=32, verbose_name='Место')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена за место')),
                ('seat_type', models.CharField(choices=[('Ordinary', 'Обычное'), ('VIP', 'ВИП'), ('Discounted', 'Уцененное')], verbose_name='Тип места')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_seats', to='events.landing', verbose_name='Посадка')),
            ],
            options={
                'verbose_name': 'Особенное место',
                'verbose_name_plural': 'Особенные места',
                'db_table': 'special_seats',
                'unique_together': {('landing', 'seat')},
            },
        ),
    ]
