# Generated by Django 4.2 on 2024-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_landing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialseat',
            name='seat_type',
            field=models.CharField(choices=[('vip', 'ВИП'), ('discounted', 'Уцененное')], verbose_name='Тип места'),
        ),
    ]
