# Generated by Django 4.2 on 2024-08-28 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('event_name', models.CharField(verbose_name='Наименование мероприятия')),
                ('section', models.CharField(blank=True, max_length=64, null=True, verbose_name='Секция')),
                ('row', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ряд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена за место')),
                ('seat', models.CharField(max_length=32, verbose_name='Место')),
                ('status', models.CharField(choices=[('Active', 'Активный'), ('Used', 'Использованный'), ('Expired', 'Просроченный')], default=('Active', 'Активный'), verbose_name='Статус использования')),
                ('bought_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время покупки')),
                ('landing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.landing', verbose_name='Посадка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'db_table': 'tickets',
            },
        ),
    ]
