# Generated by Django 4.2 on 2024-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(blank=True, verbose_name='Наименование мероприятия'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Цена за место'),
        ),
    ]
