# Generated by Django 4.2 on 2024-09-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_specialseat_seat_type'),
        ('tickets', '0003_alter_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='landing',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.event', verbose_name='Посадка'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('used', 'Использованный'), ('expired', 'Просроченный')], default=('active', 'Активный'), verbose_name='Статус использования'),
        ),
    ]
