# Generated by Django 4.2 on 2024-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_landing_ticket_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notification_status',
            field=models.CharField(choices=[('no notify', 'Не оповещен'), ('3 days', 'За 3 дня'), ('day in day', 'День в день'), ('expired', 'Просроченный')], default=('no notify', 'Не оповещен'), verbose_name='Статус оповещения'),
        ),
    ]
