# Generated by Django 4.2 on 2024-10-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_specialseat_seat_type'),
        ('tickets', '0005_ticket_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='check_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество попыток проверки'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего обновления статуса'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notification_status',
            field=models.CharField(blank=True, choices=[('no_notify', 'Не оповещен'), ('3_days', 'За 3 дня'), ('day_in_day', 'День в день'), ('expired', 'Просроченный')], default=('no_notify', 'Не оповещен'), verbose_name='Статус оповещения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена за место'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.CharField(max_length=64, null=True, verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='section',
            field=models.CharField(max_length=64, null=True, verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Ожидание оплаты'), ('active', 'Активный'), ('used', 'Использованный'), ('expired', 'Просроченный'), ('canceled', 'Отмененный')], default=('active', 'Активный'), verbose_name='Статус использования'),
        ),
    ]
