# Generated by Django 4.2 on 2024-10-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_check_count_ticket_status_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acquiring_status',
            field=models.CharField(default='COMPLETED', verbose_name='Статус эквайринга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Ожидание оплаты'), ('active', 'Активный'), ('used', 'Использованный'), ('expired', 'Просроченный'), ('canceled', 'Отмененный')], default='active', verbose_name='Статус использования'),
        ),
    ]
