# Generated by Django 4.2 on 2024-10-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_acquiring_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_id',
            field=models.CharField(default='123456', verbose_name='Id платежа'),
            preserve_default=False,
        ),
    ]
