# Generated by Django 4.2 on 2024-10-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='refund_id',
            field=models.CharField(blank=True, null=True, verbose_name='Id возрата'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notification_status',
            field=models.CharField(blank=True, choices=[('no_notify', 'Не оповещен'), ('3_days', 'За 3 дня'), ('day_in_day', 'День в день'), ('expired', 'Просроченный')], default='no_notify', verbose_name='Статус оповещения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('unknown', 'Неизвестный'), ('waiting', 'Ожидание оплаты'), ('active', 'Активный'), ('used', 'Использованный'), ('expired', 'Просроченный'), ('canceled', 'Отмененный'), ('no refund', 'Не нужен возврат'), ('need refund', 'Нужен возврат'), ('waiting refund', 'Ожидание возврата'), ('success refund', 'Удачный возврат'), ('fail refund', 'Ошибка возврата')], default='active', verbose_name='Статус'),
        ),
    ]
