# Generated by Django 4.2 on 2024-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_refund_id_alter_ticket_notification_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='bought_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('unknown', 'Неизвестный'), ('waiting', 'Ожидание оплаты'), ('active', 'Активный'), ('used', 'Использованный'), ('expired', 'Просроченный'), ('canceled', 'Отмененный'), ('need refund', 'Нужен возврат'), ('waiting refund', 'Ожидание возврата'), ('success refund', 'Удачный возврат'), ('fail refund', 'Ошибка возврата')], default='active', verbose_name='Статус'),
        ),
    ]
