# Generated by Django 4.2 on 2024-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_rename_bought_at_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bought_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время покупки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
    ]
