# Generated by Django 4.2 on 2024-10-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_specialseat_seat_type'),
        ('tickets', '0011_ticket_bought_at_alter_ticket_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_timeout', models.PositiveIntegerField(default=900, verbose_name='Время жизни временной брони')),
                ('payment_timeout', models.PositiveIntegerField(default=180, verbose_name='Время жизни платежа')),
                ('payment_attempts_number', models.PositiveIntegerField(default=20, verbose_name='Количество попыток проверки платежа')),
            ],
            options={
                'verbose_name': 'Настройки билетов',
                'db_table': 'tickets_settings',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('unknown', 'Неизвестный'), ('waiting', 'Ожидание оплаты'), ('active', 'Активный'), ('used', 'Использованный'), ('expired', 'Просроченный'), ('canceled', 'Отмененный'), ('need_refund', 'Нужен возврат'), ('waiting_refund', 'Ожидание возврата'), ('success_refund', 'Удачный возврат'), ('fail_refund', 'Ошибка возврата')], default='active', verbose_name='Статус'),
        ),
    ]
