# Generated by Django 4.2 on 2024-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('confirm_email', 'Подтверждение адреса электронной почты'), ('password_restore', 'Восстановление пароля'), ('notify_day_in_day', 'Оповещение день в день'), ('notify_3_days', 'Оповещенеи за 3 дня'), ('notify_expired', 'Оповещение о просроченном билете')], max_length=64, unique=True, verbose_name='Тип письма'),
        ),
    ]
